; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
lib_ignore =
    DueFlashStorage
    WiFi101
build_flags =
    -DWEBSOCKETS_USE_ETHERNET=true
    -DUSE_QN_ETHERNET=true
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    ssilverman/QNEthernet@^0.29.0
    khoih-prog/WebSockets2_Generic@^1.13.2
    https://github.com/joepasquariello/FlasherX.git
